const functions = require('firebase-functions');

// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
// exports.helloWorld = functions.https.onRequest((request, response) => {
//   functions.logger.info("Hello logs!", {structuredData: true});
//   response.send("Hello from Firebase!");
// });

const admin = require('firebase-admin');
const nodemailer = require('nodemailer');
//const cors = require('cors')({ origin: true });

//Initializing Firebase Admin SDK
admin.initializeApp();


//Creating Nodemailer transporter using your Mailtrap SMTP details
let transporter = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 587,
    ssl: false,
    tls: true,//use TSL
    auth: {
      user: "recruitmentwebsite1@gmail.com", // generated by Mailtrap
      pass: "Recruit1" // generated by Mailtrap
    }
  });


//Creating a Firebase Cloud Function
  exports.emailSender = functions.https.onRequest((req, res) => {
/*
    cors(req, res, () => {
        if (req.method !== 'POST') {
          return;
        }
*/
    const mailOptions = {
        from: "steven.fauterre@laposte.net", //Adding sender's email
        to: req.query.dest, //Getting recipient's email by query string
        subject: 'Email Sent via Firebase test', //Email subject
        html: '<b>Sending emails with Firebase is easy!</b>' //Email content in HTML
    };

    return transporter.sendMail(mailOptions, (err, info) => {
        if(err){
            return res.send(err.toString());
        }
        return res.send('Email sent successfully');
    });
    });
 // });

  //https://us-central1-bdd-recruitement-website.cloudfunctions.net/emailSender?dest=recruitmentwebsite1@gmail.com